### ISSUE TITLE
Make compatible with Neos 5.x

### ISSUE THREAD

**Issue by kdambekalns** [flownative/neos-multisitehelper#2]

**Comment by mbiberger** [comment]
Hi Karsten,

can you adjust please the `SecurityLoggerInterface` in `PersistedUsernamePasswordProvider.php`?
Because the legacy logger was remove in flow 6.0.

https://flowframework.readthedocs.io/en/6.0/TheDefinitiveGuide/PartV/ChangeLogs/600.html#id138

Thank you again
Markus
